name: file-system-tree
base: core18 # the base snap is the execution environment for this snap
version: '1.6.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: a detailed implementation of the well-known CLI application 'tree'
description: |
  This program is a more detailed implementation of the well-known CLI application 'tree' pre-installed on most of operating systems.

  The executable compiled for distros of Debian family may also be executed on some distros of other Linux families such as Manjaro, which is of Arch family.

grade: stable
confinement: strict

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: python
